### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hilaluzunoglu** [sorenwacker/ms-mint#1]
Hello, first of all congratulations for the application. I tried to run the application but got an error. First of all, the application is constantly updating itself in the part with dash. Secondly, when it comes to the upload data part, the following calback error appears.

Callback error updating {"index": "ms-uploader-output", "type": "output"}, "children"
TypeError: expected str, bytes or os.PathLike object, not list
fn_new = P(ms_dir) / P(fn).name
I couldn't run it, it seems to load the data, but it doesn't, giving these errors.

(I guess P(fn).name doesn't see it as path.)

**Comment by sorenwacker** [comment]
Hi, 

the updating is expected as the frontend loads the status from the backend in regular intervals. That is not an error. 

Which versions of ms-mint and ms-mint app are you using? Try uploading it to the newest version. If you see this callback error, do you running the app in debug mode? 

Could you add a screenshot?

**Comment by sorenwacker** [comment]
This is an outdated repository. The ms-mint-app is now here:

https://github.com/LewisResearchGroup/ms-mint-app
