### ISSUE TITLE
504 Gateway Time-out nginx/1.18.0 (Ubuntu)

### ISSUE THREAD

**Issue by CAMILA-MEIRA** [sorenwacker/ms-mint#29]
Hi Soren,

Every time I run MINT after picking peaks, I get this error 504 Gateway Time-out nginx/1.18.0 (Ubuntu). Could you please fix it for me? I want to download the results from Promastigotes_spent_media workspace.

    MINT version: 0.0.53 65.gd5fff28.dirty
    OS: Linux-5.4.0-77-generic-x86_64-with-debian-10.10
    Versions: ---

**Comment by soerendip** [comment]
Hi, 

I saw the peaklist has no values in the `rt_min` and `rt_max` columns. Something seems to be wrong with your peak picking. 
When there is no value MINT extracts the whole chromatogram for each peak and file which is to much to store in memory for the small VM. Mint actually relies on `rt_min` and `rt_max`. 

![image](https://user-images.githubusercontent.com/3391614/126565559-731df789-9b4f-44df-8944-437b84817c21.png)

**Comment by soerendip** [comment]
![image](https://user-images.githubusercontent.com/3391614/126565898-bf7365c3-5c7a-4544-9c97-fd9e4e2a5be8.png)
This is how your peaks look at the moment. Try to zoom in to the peak that you are actually interested in and set the `rt_min` and `rt_max` before you run Mint.

**Comment by soerendip** [comment]
I just went through a few peaks and clicked on 'Set RT to current view' and this is how it looks like now: 
![image](https://user-images.githubusercontent.com/3391614/126566917-d38de30d-615d-4b78-8cc8-2e0b91e50819.png)
![image](https://user-images.githubusercontent.com/3391614/126566952-94ef863f-bb06-47f6-b737-cccc3de862bc.png)

**Comment by soerendip** [comment]
I think if the `rt_min` and `rt_max` values are not set a default margin is displayed. If you set the RT values by clicking on `Confirm RT` you may click on the `Find largest peak for all` button. That should set the values for most peaks.
